"""Terraform module generation for CostSentinel infrastructure."""

from __future__ import annotations

import json
from typing import Any, Dict, Optional


class TerraformModuleGenerator:
    """Generates Terraform/CDK module for CostSentinel deployment.

    Produces HCL-compatible configuration for DynamoDB, Lambda Layer,
    IAM roles, and CloudWatch resources.
    """

    def __init__(
        self,
        project_name: str = "costsentinel",
        region: str = "us-east-1",
        stage: str = "dev",
    ):
        self.project_name = project_name
        self.region = region
        self.stage = stage

    def generate_main_tf(self) -> str:
        """Generate main.tf content.

        Returns:
            HCL string for the main Terraform configuration.
        """
        return f'''# CostSentinel Infrastructure - {self.project_name} ({self.stage})
# Generated by CostSentinel deployment module

terraform {{
  required_version = ">= 1.0"
  required_providers {{
    aws = {{
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }}
  }}
}}

provider "aws" {{
  region = var.region
}}

# DynamoDB table for cost state tracking
resource "aws_dynamodb_table" "cost_state" {{
  name         = "${{var.project_name}}-state-${{var.stage}}"
  billing_mode = "PAY_PER_REQUEST"
  hash_key     = "pk"
  range_key    = "sk"

  attribute {{
    name = "pk"
    type = "S"
  }}

  attribute {{
    name = "sk"
    type = "S"
  }}

  ttl {{
    attribute_name = "ttl"
    enabled        = true
  }}

  tags = {{
    Project = var.project_name
    Stage   = var.stage
    ManagedBy = "costsentinel"
  }}
}}

# Lambda Layer for CostSentinel middleware
resource "aws_lambda_layer_version" "costsentinel" {{
  layer_name          = "${{var.project_name}}-layer-${{var.stage}}"
  description         = "CostSentinel cost governance middleware"
  compatible_runtimes = ["python3.9", "python3.10", "python3.11", "python3.12"]
  filename            = "${{path.module}}/layer.zip"
  source_code_hash    = filebase64sha256("${{path.module}}/layer.zip")
}}

# IAM role for CostSentinel functions
resource "aws_iam_role" "costsentinel_role" {{
  name = "${{var.project_name}}-role-${{var.stage}}"

  assume_role_policy = jsonencode({{
    Version = "2012-10-17"
    Statement = [{{
      Action = "sts:AssumeRole"
      Effect = "Allow"
      Principal = {{
        Service = "lambda.amazonaws.com"
      }}
    }}]
  }})
}}

resource "aws_iam_role_policy" "costsentinel_policy" {{
  name = "${{var.project_name}}-policy-${{var.stage}}"
  role = aws_iam_role.costsentinel_role.id

  policy = jsonencode({{
    Version = "2012-10-17"
    Statement = [
      {{
        Effect = "Allow"
        Action = [
          "dynamodb:GetItem",
          "dynamodb:PutItem",
          "dynamodb:UpdateItem",
          "dynamodb:Query",
        ]
        Resource = aws_dynamodb_table.cost_state.arn
      }},
      {{
        Effect = "Allow"
        Action = [
          "cloudwatch:PutMetricData",
        ]
        Resource = "*"
      }},
      {{
        Effect = "Allow"
        Action = [
          "logs:CreateLogGroup",
          "logs:CreateLogStream",
          "logs:PutLogEvents",
        ]
        Resource = "arn:aws:logs:*:*:*"
      }}
    ]
  }})
}}
'''

    def generate_variables_tf(self) -> str:
        """Generate variables.tf content."""
        return f'''variable "project_name" {{
  description = "Project name for resource naming"
  type        = string
  default     = "{self.project_name}"
}}

variable "stage" {{
  description = "Deployment stage (dev/staging/prod)"
  type        = string
  default     = "{self.stage}"
}}

variable "region" {{
  description = "AWS region"
  type        = string
  default     = "{self.region}"
}}
'''

    def generate_outputs_tf(self) -> str:
        """Generate outputs.tf content."""
        return '''output "state_table_name" {
  value       = aws_dynamodb_table.cost_state.name
  description = "DynamoDB table name for cost state"
}

output "state_table_arn" {
  value       = aws_dynamodb_table.cost_state.arn
  description = "DynamoDB table ARN"
}

output "layer_arn" {
  value       = aws_lambda_layer_version.costsentinel.arn
  description = "Lambda Layer ARN for CostSentinel"
}

output "role_arn" {
  value       = aws_iam_role.costsentinel_role.arn
  description = "IAM role ARN for CostSentinel functions"
}
'''

    def generate_all(self) -> Dict[str, str]:
        """Generate all Terraform files.

        Returns:
            Dict mapping filename to content.
        """
        return {
            "main.tf": self.generate_main_tf(),
            "variables.tf": self.generate_variables_tf(),
            "outputs.tf": self.generate_outputs_tf(),
        }

    def write_module(self, output_dir: str = "infrastructure/terraform") -> None:
        """Write all Terraform files to a directory.

        Args:
            output_dir: Directory to write files to.
        """
        import os
        os.makedirs(output_dir, exist_ok=True)
        for filename, content in self.generate_all().items():
            with open(os.path.join(output_dir, filename), "w") as f:
                f.write(content)
